### ISSUE TITLE
Add RSeQC junction_annotation and junction_saturation

### ISSUE THREAD

**Issue by kopardev** [CCBR/SBG_partners#1]
SF has 2 extra apps that should be added to the SBG WF

**Comment by skchronicles** [comment]
### Changes to create a universal pipeline between CCBR and SF:

# Junction Annotation  
For a given alignment file (-i) in BAM or SAM format and a reference gene model (-r) in BED format, this program will compare detected splice junctions to reference gene model. splicing annotation is performed in two levels: splice event level and splice junction level.
http://rseqc.sourceforge.net/#junction-annotation-py

# Junction Saturation  
It’s very important to check if current sequencing depth is deep enough to perform alternative splicing analyses. For a well annotated organism, the number of expressed genes in particular tissue is almost fixed so the number of splice junctions is also fixed. The fixed splice junctions can be predetermined from reference gene model. All (annotated) splice junctions should be rediscovered from a saturated RNA-seq data, otherwise, downstream alternative splicing analysis is problematic because low abundance splice junctions are missing. This module checks for saturation by resampling 5%, 10%, 15%, ..., 95% of total alignments from BAM or SAM file, and then detects splice junctions from each subset and compares them to reference gene model.
http://rseqc.sourceforge.net/#junction-saturation-py

**Comment by skchronicles** [comment]
## RESOLVED:
### RSeQC Junction Annotation app can be found here:
https://cgc.sbgenomics.com/u/Durga/rna-seq-ccbr/apps/#Durga/rna-seq-ccbr/rseqc-junction-annotation-2-6-4
- Output filename is dynamically determined from the input bam filename . 
### RSeQC Junction Saturation app can be found here:
https://cgc.sbgenomics.com/u/Durga/rna-seq-ccbr/apps/#Durga/rna-seq-ccbr/rseqc-junction-saturation-2-6-4
- Output filename is dynamically determined from the input bam filename
